#! /bin/sh

sxhkd &
polybar mybar &
bspc monitor -d I II III IV V VI VII VIII IX X

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP1 --auto --output "HDMI-1" --same-as "eDP-1"
fi

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
